### ISSUE TITLE
scrambled images

### ISSUE THREAD

**Issue by darodi** [Harkame/JapScanDownloader#2]
There is some kind of protection on images now.

The following looks fine in a browser
https://www.japscan.to/lecture-en-ligne/shingeki-no-kyojin/112/2.html

however, the dowloaded image is scrambled.
https://c.japscan.to/clel/Shingeki-No-Kyojin/112/02.jpg

somebody did a decoding in python, this thread might help

https://github.com/inorichi/tachiyomi-extensions/issues/698

**Comment by Harkame** [comment]
Thanks for your help ! I think I will activate this feature by default
