### ISSUE TITLE
Pages not downloaded in the correct order

### ISSUE THREAD

**Issue by Starjunh** [Harkame/JapScanDownloader#25]
Hello,

Everything works fine, my libraries are those required in requirement.txt, but pages are not ordered correctly in the generated pdfs and I really do not know why. It doesn't seem to follow any kind of sorting so I do not understand why it doesn't work. Here is an example for a chapter:
[60.pdf](https://github.com/Harkame/JapScanDownloader/files/3291817/60.pdf)

Edit: It occurs with .pdf  (I have tried and it works fine with a jpg format)

**Comment by Harkame** [comment]
Hi, thanks for your feedback.

Bug resolved, this problem was because of a bad ordering files recuperation, before pdf or cbz creation.
