### ISSUE TITLE
Mise à jour de prévu ?

### ISSUE THREAD

**Issue by RGFRv2** [Harkame/JapScanDownloader#30]
Bonjour, 

Je voudrais savoir si une mise à jour est prévu ? 

Car lorsque je lance le script rien ne se télécharge (j'ai crée les répertoires de téléchargement)

**Comment by Harkame** [comment]
Salut,

En effet, ils ont rajouté une bonne grosse couche d'offuscation, je vais regarder si il y a un truc à faire en utilisant selenium

**Comment by RGFRv2** [comment]
Ca serait cool si y'a moyen de dl à nouveau :)

**Comment by Harkame** [comment]
Il y a encore pas mal de bug mais ça à l'air de fonctionner,

Maintenant il faut Google Chrome et ChromeDriver (https://chromedriver.chromium.org)

Et la commande est : python japscandownloader\main.py -D D:\chromedriver.exe

**Comment by RGFRv2** [comment]
Salut, faut le récupérer depuis la branche DEV ou il va y avoir un merge sur la master ?

**Comment by Harkame** [comment]
Ah mb, je vais merge, par contre je viens de voir que pour Chrome il faut avoir un anti pub, j'utilise ublock origin perso

**Comment by RGFRv2** [comment]
J'ai vu ça, par contre ça peut s'intégrer sur un Webdriver une extension ?

**Comment by Harkame** [comment]
C'est un truc que je regarderai pour l'histoire de l'anti pub, mais ouai, ça va lancer Chrome avec le profile utilisateur (extensions, favoris, etc). Le seul pb c'est que le webdriver ne se lance que si Chrome n'est pas déjà lancé

**Comment by RGFRv2** [comment]
J'ai installé Ublock sur le Profile qu'il utilise et voilà ce que j'ai maintenant :

```
F:\GIT\JapScanDownloader (dev -> origin)
python japscandownloader\main.py -D chromedriver.exe

DevTools listening on ws://127.0.0.1:58226/devtools/browser/d7c4b331-162c-410b-acc7-1c92ad1aa2de
/lecture-en-ligne/shingeki-no-kyojin/60/1.html
/lecture-en-ligne/shingeki-no-kyojin/60/2.html
/lecture-en-ligne/shingeki-no-kyojin/60/3.html
/lecture-en-ligne/shingeki-no-kyojin/60/4.html
/lecture-en-ligne/shingeki-no-kyojin/60/5.html
/lecture-en-ligne/shingeki-no-kyojin/60/6.html
/lecture-en-ligne/shingeki-no-kyojin/60/7.html
/lecture-en-ligne/shingeki-no-kyojin/60/8.html
/lecture-en-ligne/shingeki-no-kyojin/60/9.html
/lecture-en-ligne/shingeki-no-kyojin/60/10.html
/lecture-en-ligne/shingeki-no-kyojin/60/11.html
/lecture-en-ligne/shingeki-no-kyojin/60/12.html
/lecture-en-ligne/shingeki-no-kyojin/60/13.html
/lecture-en-ligne/shingeki-no-kyojin/60/14.html
/lecture-en-ligne/shingeki-no-kyojin/60/15.html
/lecture-en-ligne/shingeki-no-kyojin/60/16.html
/lecture-en-ligne/shingeki-no-kyojin/60/17.html
/lecture-en-ligne/shingeki-no-kyojin/60/18.html
/lecture-en-ligne/shingeki-no-kyojin/60/19.html
/lecture-en-ligne/shingeki-no-kyojin/60/20.html
/lecture-en-ligne/shingeki-no-kyojin/60/21.html
/lecture-en-ligne/shingeki-no-kyojin/60/22.html
/lecture-en-ligne/shingeki-no-kyojin/60/23.html
/lecture-en-ligne/shingeki-no-kyojin/60/24.html
/lecture-en-ligne/shingeki-no-kyojin/60/25.html
/lecture-en-ligne/shingeki-no-kyojin/60/26.html
/lecture-en-ligne/shingeki-no-kyojin/60/27.html
/lecture-en-ligne/shingeki-no-kyojin/60/28.html
/lecture-en-ligne/shingeki-no-kyojin/60/29.html
/lecture-en-ligne/shingeki-no-kyojin/60/30.html
/lecture-en-ligne/shingeki-no-kyojin/60/31.html
/lecture-en-ligne/shingeki-no-kyojin/60/32.html
/lecture-en-ligne/shingeki-no-kyojin/60/33.html
/lecture-en-ligne/shingeki-no-kyojin/60/34.html
/lecture-en-ligne/shingeki-no-kyojin/60/35.html
/lecture-en-ligne/shingeki-no-kyojin/60/36.html
/lecture-en-ligne/shingeki-no-kyojin/60/37.html
/lecture-en-ligne/shingeki-no-kyojin/60/38.html
/lecture-en-ligne/shingeki-no-kyojin/60/39.html
/lecture-en-ligne/shingeki-no-kyojin/60/40.html
/lecture-en-ligne/shingeki-no-kyojin/60/41.html
/lecture-en-ligne/shingeki-no-kyojin/60/42.html
/lecture-en-ligne/shingeki-no-kyojin/60/43.html
/lecture-en-ligne/shingeki-no-kyojin/60/44.html
/lecture-en-ligne/shingeki-no-kyojin/60/45.html
/lecture-en-ligne/shingeki-no-kyojin/60/46.html
                                                                                                                                                                                                                                             data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255, 255, 255, 0.9)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E
Traceback (most recent call last):
  File "japscandownloader\main.py", line 12, in <module>
    japscan_downloader.download(manga)
  File "F:\GIT\JapScanDownloader\japscandownloader\jss_selenium.py", line 203, in download
    self.download_chapter(chapter)
  File "F:\GIT\JapScanDownloader\japscandownloader\jss_selenium.py", line 281, in download_chapter
    file = self.download_page(chapter_path, page_url, index)
  File "F:\GIT\JapScanDownloader\japscandownloader\jss_selenium.py", line 366, in download_page
    response = self.scraper.get(image_url)
  File "F:\GIT\JapScanDownloader\env\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "F:\GIT\JapScanDownloader\env\lib\site-packages\cloudscraper\__init__.py", line 123, in request
    resp = super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "F:\GIT\JapScanDownloader\env\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\GIT\JapScanDownloader\env\lib\site-packages\requests\sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "F:\GIT\JapScanDownloader\env\lib\site-packages\requests\sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255, 255, 255, 0.9)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E'
[                                                                   ] - [0/46] - [pages]
```

**Comment by Krylanc3lo** [comment]
Merci beaucoup! je vais tester aussi de mon cote

**Comment by Harkame** [comment]
Je viens de faire pas mal de modifs, normalement plus besoin d'anti pub obligatoirement, et plus d'utilisation du profil utilisateur donc plus besoin d'arrêter chrome

Il y a encore 2 bugs que j'ai vus mais pas encore fix, la première image du chapitre qui est soit mauvaise soit en double, et un bug lié au maximum de retry de connexions pour avoir l'image

**Comment by RGFRv2** [comment]
Tu saurais comment fix cette erreur ? 
```
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2j  26 Sep 2016) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
```

**Comment by Harkame** [comment]
Ça m'arrive de temps en temps, je relance le script et c'est bon. J'utilise cloudscraper pour le téléchargement de l'image psk qu'il est plus souvent MAJ que cfscrape. Après c'est un pb que j'ai souvent eu même sur d'autres projets et si il persiste soit il faut une MAJ de clouscraper soit et ça m'est déjà arrivé, un pb avec un package sur mon PC, une version d'urllib qui posait pb dans mon cas, là j'ai urllib3==1.25.8 et ça fonctionne chez moi. Mais temps mieux si cfscrape fonctionne

**Comment by Krylanc3lo** [comment]
Merci beaucoup pour la mise a jour!

je suis sous ubuntu et j'ai cette erreur:

```~/downloads/JapScanDownloader-master$ python japscandownloader/main.py -D ./chromedriver
Traceback (most recent call last):
  File "japscandownloader/main.py", line 1, in <module>
    import cloudscraper
ImportError: No module named cloudscraper```

Pourtant j'ai bien cloudscraper:

```~/downloads/JapScanDownloader-master$ pip show cloudscraper
Name: cloudscraper
Version: 1.2.28
```

est-ce que tu as une idee ?

Merci encore pour l'aide!

**Comment by Harkame** [comment]
J'ai pas encore testé sous Linux donc je ne garantis rien surtout pour le WebDriver,

Tu as bien installé les packages avec la commande pip install -r requirements.txt -U ?

**Comment by Krylanc3lo** [comment]
oui c'est bon, tout fonctionne maintenant (ma commande python pointait vers 2.7, en utilisant python3  pour lancer, tout marche bien!).

j'ai juste un warning au lancement mais rien de bloquant

```python3 japscandownloader/main.py -D ./chromedriver
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
```

et j'essaie de voir comment mettre un antipub sur la version qui se lance via selenium (je l'ai sur chrome mais quand je lance selenium, il ne semble pas s'activer).

Ca fonctionne super bien en tout cas merci!

**Comment by Harkame** [comment]
Pas de soucis

Comme je l'ai dit https://github.com/Harkame/JapScanDownloader/issues/30#issuecomment-599364160, normalement il n'y a plus besoin d'anti pub mais si tu veux quand même en mettre un, il faut utiliser le profile où sont installés les extensions pour ça il faut juste décommenter la ligne 77 dans le fichier jss_selenium.py : options.add_argument("--user-data-dir=/home/username/.config/google-chrome")

Je rajouterais la possibilité d'utiliser le profile utilisateur avec une option un peu plus tard

**Comment by RGFRv2** [comment]
https://github.com/Harkame/JapScanDownloader/blob/6721fbf5848456d1e0792682356acb465fc61c0f/japscandownloader/jss_selenium.py#L287
`logger.debug(f"error self.driver.get({page_url}) retry")` 

Et concernant cloudflare, ça ne serait plus intéressant de faire un fichier cookies qui contient la session et qu'on aura juste à appeler dans la request

https://github.com/Harkame/JapScanDownloader/blob/6721fbf5848456d1e0792682356acb465fc61c0f/japscandownloader/jss_selenium.py#L276

Je l'ai remplacé par `time.sleep(randint(1,5))` comme ça le sleep est variable et ça peut possiblement éviter l'erreur de timeout.

**Comment by Krylanc3lo** [comment]
Merci encore pour le fix ;)
