### ISSUE TITLE
images de taille 0 byte

### ISSUE THREAD

**Issue by darodi** [Harkame/JapScanDownloader#33]
Bonjour,

Je viens de tester la dernière version.
Je lance le script avec la commande:
`japscandownloader/main.py -D C:\\downloads\\chromedriver.exe -v`

pour l'entrée:
`  - chapter :
      https://www.japscan.co/lecture-en-ligne/radiant/93/`

chrome s'ouvre, rentre sur chaque page du chapitre du manga mais les images ne s'y affichent pas et les fichiers téléchargés font 0 byte.

Le script fonctionne-t-il toujours?

Merci d'avance pour les précisions.

Darodi

**Comment by Harkame** [comment]
Salut, problème résolu pour l'histoire des images qui font 0 byte. Comme par hasard Japscan avait rajouté une sécurité si le navigateur était controlé par un WebDriver, les images n'étaient pas téléchargées. En revanche pour l'exemple de Radiant, les images sont brouillées et l'algo je ne pense pas que l'algo de débrouillage actuel soit toujours bon, il faut que je regarde pour le modifier, ou trouver un meilleur moyen de récupérer les images.
