### ISSUE TITLE
Headless not working anymore

### ISSUE THREAD

**Issue by Krylanc3lo** [Harkame/JapScanDownloader#40]
Hello,

I hope you are doing well. Japscan moved to a new domain (japscan.me) and the headless option does not work anymore. I got the below error message:

```
selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot take screenshot with 0 width."}
  (Session info: headless chrome=85.0.4183.121)
```

It is working without headless but the image are not complete.

Here is the configuration:

```
options = webdriver.ChromeOptions()
options.add_argument("--log-level=3")
options.add_argument("--disable-blink-features")
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument("window-size=1440,2560")
options.add_argument("--headless")
options.add_experimental_option("excludeSwitches", ["enable-logging"])
options.add_experimental_option("useAutomationExtension", False)
options.add_experimental_option("excludeSwitches", ["enable-automation"])
```

Do you have an idea ? is it because of the ads ? if so it seems similar to the issue #38 (sorry if it is the case)

Thanks a lot for your help, as usual!

**Comment by Krylanc3lo** [comment]
Hello,

Nevermind, it is working well except for 2 chapters, most likely due to their migration to a new domain.

thank you!

**Comment by Harkame** [comment]
Hi ! thanks for the details
It seem to block for certain chapter : https://www.japscan.se/lecture-en-ligne/black-clover/161/ in my case
I've added a simple try/except to avoid crash

Just make sure you are using 1.0.5 version

If you are using a fork, please see this commit https://github.com/Harkame/JapScanDownloader/commit/46584eebe284b7b63a5be2aa25e69be11d2a3eae

**Comment by Krylanc3lo** [comment]
thank you, I will update to 1.0.5 and test, it seems more and more frequent

**Comment by Krylanc3lo** [comment]
It is working very well, thaks for the try/except part. Do you know why it is not working for some chapters ? especially for the 1st pages (for new or old chapters).

I can create a new issue if you prefer :)

**Comment by Harkame** [comment]
I have the same problem, in my case 1s sleep resolve this problem
Your 4s sleep is random or did you test with another durations ?

IMO, the easiest solution is to add an retry, its not very clean but it works, I will add it in 1.0.6

### Old version
```python
image_element = self.driver.find_element_by_id("image")

im = None

try:
  im = Image.open(BytesIO(image_element.screenshot_as_png))
except selenium.common.exceptions.WebDriverException:
  logger.debug(f"error invalid image_element.screenshot_as_png")
```

### New version
```python
image_element = self.driver.find_element_by_id("image")
time.sleep(1)  # Sleep to load image

im = None

try:
    im = Image.open(BytesIO(image_element.screenshot_as_png))
except Exception:  # Fail on get image
    logger.debug(f"error : invalid image_element.screenshot_as_png")
    time.sleep(4)

    try:  # Retry to get image after a fail
        im = Image.open(BytesIO(image_element.screenshot_as_png))
    except Exception:
        logger.debug(f"error retry : invalid image_element.screenshot_as_png")
```
