### ISSUE TITLE
can't launch the downloader

### ISSUE THREAD

**Issue by hxhging** [Harkame/JapScanDownloader#50]
hi, when i write japscandownloader on cmd it's written FileNotFoundError: [Errno 2] No such file or directory: '.\\config.yml' can you help me ?
i tried to follow all the steps.
Thanks in advance

**Comment by Harkame** [comment]
Hi, you need to create a file called « config.yml » (example https://github.com/Harkame/JapScanDownloader/blob/master/config.yml) and execute command « japscandownloader » in the same folder
