### ISSUE TITLE
cloudflare check not passed

### ISSUE THREAD

**Issue by darodi** [Harkame/JapScanDownloader#71]
I updated chromedriver.exe a few days ago.
I don't know if this is linked, but now, the main page is not loading.

I managed to bypass the check with
https://github.com/ultrafunkamsterdam/undetected-chromedriver
instead of the usual chromedriver in python.
However, headless mode must be turned off to make it work.

Any advice?

I can create a PR if you want.

**Comment by Harkame** [comment]
I'm not surprised, I'm using undetected-chromedriver on several over scrapers
I would appreciate a PR, thank you

For the headless mode, I haven't any clues for now. maybe you can try something like move the windows out the screen
like this
``` python
driver.set_window_position(-10000,0)
```

or maybe change de windows size like this
``` python
browser.set_window_size(0, 0)
```

**Comment by darodi** [comment]
works again in headless mode with last version of undetected-chromedriver
see version changelog here
https://github.com/ultrafunkamsterdam/undetected-chromedriver#345
